# Don't print a new line at the start of the prompt
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 0

# Use custom format with adjusted separators
format = """
$username$hostname:$directory $git_branch
$character"""

# Username settings
[username]
show_always = true
style_root = "bold red"
style_user = "bold cyan"
format = "[$user]($style)"
disabled = false

# Hostname settings
[hostname]
ssh_only = false
format = "[@$hostname](bold cyan)"
disabled = false

# Directory indicator
[directory]
read_only = "🔒"
style = "bold yellow"
read_only_style = "red"
truncation_length = 8
truncation_symbol = "../"
format = "[$path]($style)"
disabled = false
